---
name: Upload Image

on:
  push:
    tags: '*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps: 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Alpine
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: |
            giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}
          build-args: CFN_LINT_VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Build and push Bullseye
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: |
            giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-bullseye
            ghcr.io/giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-bullseye
          labels: ${{ steps.meta.outputs.labels }}
          build-args: IMAGE_PREFIX=python:3.8-bullseye,CFN_LINT_VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Build and push Slim
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: |
            giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-slim
            ghcr.io/giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-slim
          labels: ${{ steps.meta.outputs.labels }}
          build-args: IMAGE_PREFIX=python:3.8-slim,CFN_LINT_VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Build and push Buster
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: |
            giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-buster
            ghcr.io/giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-buster
          labels: ${{ steps.meta.outputs.labels }}
          build-args: IMAGE_PREFIX=python:3.8-buster,CFN_LINT_VERSION=${{ steps.get_version.outputs.VERSION }}