name: Upload DockerHub Image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for latest and alpine version
        id: meta-latest
        uses: docker/metadata-action@3.5.0
        with:
          images: giammbo/cfn-lint

      - name: Extract metadata (tags, labels) for other version
        id: meta
        uses: docker/metadata-action@3.5.0
        with:
          images: giammbo/cfn-lint
          flavor: |
            latest=false

      - name: Build and push Alpine
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta-latest.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Bullseye
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-bullseye
          labels: ${{ steps.meta.outputs.labels }}
          build-args: IMAGE_PREFIX=python:3.8-bullseye

      - name: Build and push Slim
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-slim
          labels: ${{ steps.meta.outputs.labels }}
          build-args: IMAGE_PREFIX=python:3.8-slim

      - name: Build and push Buster
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-buster
          labels: ${{ steps.meta.outputs.labels }}
          build-args: IMAGE_PREFIX=python:3.8-buster