---
name: Upload Image

on:
  push:
    tags: '*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps: 

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Alpine
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          tags: |
            giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}
            giammbo/cfn-lint:latest
            ghcr.io/giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/giammbo/cfn-lint:latest
          build-args: CFN_LINT_VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Test Alpine
        run: docker -v $(pwd)/:/opt/ run giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }} /opt/tests/template.yaml

      - name: Build Bullseye
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          tags: |
            giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-bullseye
            ghcr.io/giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-bullseye
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_PREFIX=python:3-bullseye
            CFN_LINT_VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Test Bullseye
        run: docker -v $(pwd)/:/opt/ run giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-bullseye /opt/tests/template.yaml

      - name: Build Slim
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          tags: |
            giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-slim
            ghcr.io/giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-slim
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_PREFIX=python:3-slim
            CFN_LINT_VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Test Slim
        run: docker -v $(pwd)/:/opt/ run giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-slim /opt/tests/template.yaml

      - name: Build Buster
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          tags: |
            giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-buster
            ghcr.io/giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-buster
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_PREFIX=python:3-buster
            CFN_LINT_VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Test Buster
        run: docker -v $(pwd)/:/opt/ run giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-buster /opt/tests/template.yaml

      # PUSH SECTION

      - name: Push Alpine
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}
            giammbo/cfn-lint:latest
            ghcr.io/giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/giammbo/cfn-lint:latest
          build-args: CFN_LINT_VERSION=${{ steps.get_version.outputs.VERSION }}

      
      - name: Push Bullseye
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-bullseye
            ghcr.io/giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-bullseye
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_PREFIX=python:3-bullseye
            CFN_LINT_VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Push Slim
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-slim
            ghcr.io/giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-slim
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_PREFIX=python:3-slim
            CFN_LINT_VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Push Buster
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-buster
            ghcr.io/giammbo/cfn-lint:${{ steps.get_version.outputs.VERSION }}-buster
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_PREFIX=python:3-buster
            CFN_LINT_VERSION=${{ steps.get_version.outputs.VERSION }}
